### PR TITLE
TAP 1.4.1 minor release

### PR DESCRIPTION
**Pull request by satya-dillikar**
*Issue #, if available:*

*Description of changes:*

TAP Version 1.4.1
  - The stack reports back if the TAP deployment and the installation of the  sample application succeeded after all the infrastructure has been deployed
-  Deletion issues, where VPCs could not be cleaned up because of left-over  security groups has been fixed

- Version upgrades to:
   -  TAP  1.4.1
   - ClusterEssentials 1.4
   - EKS QuickStart 5.0.0
   - EKS 1.24

- Removed configuration options for:
  - Version of TAP
  - Version of EKS
  - Linux Bastion host AMI
  -  Linux Bastion host's SSH port
  - Sample application name

-  The download of artifacts (e.g. `kubectl`) has been fixed for regions other than `us-east-1`

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by satya-dillikar** [comment]
@tlindsay42 , please start e2e-tests and then merge.

**Comment by tlindsay42** [comment]
`PhaseCloudInit` and `PhaseTAPInstall` failing in all regions. Will run one more once cleaned up.

**Comment by satya-dillikar** [comment]
> `PhaseCloudInit` and `PhaseTAPInstall` failing in all regions. Will run one more once cleaned up.

This needs the shared account and regional resources CFT cleanup. On your next run, Please share errors, so that we can narrow down the cause.

**Comment by tlindsay42** [comment]
> > `PhaseCloudInit` and `PhaseTAPInstall` failing in all regions. Will run one more once cleaned up.
> 
> This needs the shared account and regional resources CFT cleanup. 

Our CI cleans these up on every build.

> On your next run, Please share errors, so that we can narrow down the cause.

Will do.

**Pull request merged**
