### PR TITLE
[qs] release 1.4.2+aws.2

### PR DESCRIPTION
**Pull request by satya-dillikar**
*Issue #, if available:*

*Description of changes:*

- bump up timeout values
- Add TAP-GUI self-cert on windows EC2

> - Added googlechrome, jq, base64 packages on Windows
> - Added AWS CLI and Kubectl on Windows
> - Added tap-gui self-cert Root-CA Cert to Windows Cert Store
> - Removed Firefox as this does not use Windows Cert Store. Google and MS Edge work perfectly with Windows Cert Store
> - Increase timeout values for single-cluster to avoid wait condition timeout flakes.
> - Created common QSBastionIamRole & QSBastionSecurityGroup to be used for both Ubuntu and Windows Bastion.
> - Separated LinuxBastionSecurityGroup (for ssh) & WindowsBastionSecurityGroup (for RDP) have specific ports used for Ubuntu and Windows Bastion.
> - Added WindowsBastion Dependency on PhaseTAPTests to start Windows EC2 only after successful TAP deployment.
> - Tested TAP-GUI over HTTPS in single-cluster and multi-cluster deployments.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by satya-dillikar** [comment]
This PR needs to go in in tandem with https://github.com/aws-quickstart/quickstart-vmware-tanzu-application-platform/pull/155

**Comment by satya-dillikar** [comment]
@tlindsay42 ,  please have a look! Thanks!

**Comment by satya-dillikar** [comment]
Hello @davmayd , Any help needed from my side?

**Comment by davmayd** [comment]
@satya-dillikar our tests are showing Lambda errors (see below) that may be related to a lack of internet access or a lack of  a VPC endpoint. It may be an issue on our end, I'm looking into it.

`<html>
<body>


Read timeout on endpoint URL: "https://lambda.us-west-2.amazonaws.com/2015-03-31/functions/cleanup-cfn/invocations"
--
3 | cat: /tmp/response: No such file or directory
4 | waiting for previous tests to clean up...


</body>
</html>`

**Comment by davmayd** [comment]
@satya-dillikar if you can confirm that testing is passing on your end I can go ahead and merge the PR

**Comment by satya-dillikar** [comment]
@davmayd,
I guess you need to a proper cleanup of your CI account.
1. Run quickstart-vmware-tanzu-application-platform/submodules/quickstart-amazon-eks/build/clean-aws.sh and 
2. manually remove IAM roles  (if any)  *quick* or *awsqs* or *CopyZips*, *DeleteBucketContents*

Yes. It passed our CI. I recommend you can merge in.
Thanks.

**Comment by satya-dillikar** [comment]
FYI, I will be off next week. But Please tag us if need more help.

**Review by davmayd — APPROVED** [review]

**Pull request merged**
