### PR TITLE
TAP 1.4.0 - All inclusive 

### PR DESCRIPTION
**Pull request by satya-dillikar**
*Issue #, if available:*

*Description of changes:*

- This PR also includes changes from  [PR-128  ](https://github.com/aws-quickstart/quickstart-vmware-tanzu-application-platform/pull/128)
- EKS 1.24 update. needed to bump the submodule EKS stack to get 1.24 support
- Remove Parameters KubernetesVersion & TAPVersion

@tlindsay42 
**Note: IF YOU MERGE THIS PR, THEN YOU CAN IGNORE PR#128**

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by tlindsay42** [comment]
@satya-dillikar Per your statement above and the content, this is the replacement for #128, right? Is so, want me to just close it now so there's no confusion later?

**Comment by satya-dillikar** [comment]
> @satya-dillikar Per your statement above and the content, this is the replacement for #128, right? Is so, want me to just close it now so there's no confusion later?

Yes.

**Comment by satya-dillikar** [comment]
if e2e ci passes, then please merge this.

**Comment by hoegaarden** [comment]
@satya-dillikar ; can you please close this PR, so there is no confusion.

This PR has been superseded by #134 ; Whatever we have in this PR and not in #134 will be tackled in a different PR.

**Comment by satya-dillikar** [comment]
closing as requested above.

**Comment by tlindsay42** [comment]
Re-opening briefly to re-run end-to-end tests after failing to duplicate in my sandbox account.

**Comment by tlindsay42** [comment]
Same wait condition timeouts for both stacks again...

**Pull request closed without merging**
