### PR TITLE
[docs] release 1.5.2+aws.3

### PR DESCRIPTION
**Pull request by leclaist**
*Issue #, if available:*

* based on current upstream
* add release note for tap 1.5.2
* change authors

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by leclaist** [comment]
This docs PR needs to go in in tandem with the PR #164

**Comment by leclaist** [comment]
@tlindsay42 @jacnnguyen

**Comment by hoegaarden** [comment]
@jacnnguyen
Thanks for merging the PR. When I go to https://aws-quickstart.github.io/quickstart-vmware-tanzu-application-platform/ , I see that this new version has not been published yet. Can you help with that? Thanks!

**Comment by jacnnguyen** [comment]
@hoegaarden, the new version should now be published.

**Pull request merged**
