### PR TITLE
[qs] release 1.4.2+aws.1

### PR DESCRIPTION
**Pull request by hoegaarden**
*Description of changes:*

user-facing changes:
- (bugfix) Relocation of  TAP container images was broken, that is fixed now
- (feature) We removed the option to specify cluster names so that name clashes are less likely
- (feature) The bastion hosts now us Instance Metadata Service Version 2 (IMDSv2)
- (feature) We changed how we check and deploy the shared resources stacks (`eks-quickstart-RegionalSharedResources` & `eks-quickstart-AccountSharedResources`) which results in a bit faster deployments and less chance to run into race-conditions

changes interesting to Troy/AWS:
- We've added more tests, we also test relocation of images now. This might mean that `.taskcat_overrides.yml` needs slight changes in AWS' CI; re. the `TanzuNetRelocateImages`

other (internal) changes:
- The bastion hosts get deployed with a launch templates and all(?)/most configuration has been moved from the instance to the launch template
- We test relocation (for single & multi cluster) in our internal pipeline
- We now use the `om` CLI instead of the `pivnet` one, because that one is supported/patched/maintained
- The timeouts we allow for the cloud-int/setup-script has been adapted for the different deployment options (multi- vs. single cluster × relocation vs. no relocation)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by hoegaarden** [comment]
@tlindsay42 please have a look! Thanks!

Note: Please have a look at the taskcat changes regarding the new tests. Not sure if you need to be aware of that, I just want to make sure your tests run with the correct config for `TanzuNetRelocateImages`

**Comment by tlindsay42** [comment]
@hoegaarden Thanks for calling that out. Checking my override config & will update if needed.

**Review by tlindsay42 — APPROVED** [review]

**Comment by tlindsay42** [comment]
@hoegaarden Will merge once #150 is ready to go

**Comment by hoegaarden** [comment]
> end to end tests passed
> @hoegaarden Will merge [...]

Sweet!

> [...] once #150 is ready to go

Great. I guess you are waiting for your doc writers on that, or is there anything you need from us / anything that's missing on #150 ?

**Comment by tlindsay42** [comment]
> Great. I guess you are waiting for your doc writers on that,...

Yep 😄 

> ...or is there anything you need from us / anything that's missing on https://github.com/aws-quickstart/quickstart-vmware-tanzu-application-platform/pull/150 ?

Nope, good-to-go from my end 🚀 🎉

**Pull request merged**
